# Generated by Django 2.2 on 2018-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=199)),
                ('photo', models.ImageField(null=True, upload_to='media/')),
                ('photo1', models.ImageField(null=True, upload_to='media/')),
                ('photo2', models.ImageField(null=True, upload_to='media/')),
                ('photo3', models.ImageField(null=True, upload_to='media/')),
                ('photo4', models.ImageField(null=True, upload_to='media/')),
                ('photo6', models.ImageField(null=True, upload_to='media/')),
                ('photo7', models.ImageField(null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'Produkt',
            },
        ),
    ]
