# Generated by Django 2.2 on 2018-08-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='prise',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo1',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo2',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo3',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo4',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo6',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='photo7',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
    ]
