# Generated by Django 2.2 on 2018-08-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0002_auto_20180810_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='photo7',
        ),
    ]
