# Generated by Django 2.2 on 2018-08-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0003_auto_20180810_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
    ]
