# Generated by Django 2.2 on 2018-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0005_auto_20180810_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='photo1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='photo2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='photo3',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
