# Generated by Django 2.0.10 on 2019-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0007_auto_20190507_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='group',
            field=models.CharField(choices=[('electronic', 'ELECTRONIK'), ('tea', 'TEA')], default='electronic', max_length=40),
        ),
    ]
