# Generated by Django 2.0.10 on 2019-05-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0013_subscribers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscribers',
            table='Subscribers',
        ),
    ]
